import { compileGraph } from './gpu-graph.js';
import { writeBundle } from './node.js';
import { rewriteIdentifiers } from './compiler.js';

/** Generate a self-contained UE Runtime plugin, with one GlobalShader per graph
 * variable and an RDG dispatcher. No WebGL context is required at runtime. */
export async function exportNativeGraph(graph, out, options = {}) {
  const compiled = await compileGraph(graph, options);
  const module = `ElfentierGpu${graph.name}`, cls = `UElfentier${graph.name}Component`, base = `Elfentier${graph.name}Component`;
  const files = new Map(), encode = text => new TextEncoder().encode(text);
  const add = (path, text) => files.set(path, encode(text));
  const uniformKeys = [], defaults = [], init = [], passClasses = [], dispatch = [];
  for (let i=0;i<compiled.passes.length;i++) {
    const {variable:v,result:r}=compiled.passes[i];
    const bytes=new Uint8Array(v.initial.length*4), view=new DataView(bytes.buffer);
    v.initial.forEach((value,j)=>view.setFloat32(j*4,value,true)); files.set(`Resources/${v.name}.bin`,bytes);
    init.push(`{ TArray<uint8> Bytes; if(!FFileHelper::LoadFileToArray(Bytes, *FPaths::Combine(BaseDir,TEXT("Resources/${v.name}.bin"))) || Bytes.Num()!=${bytes.length}) return false;
      UTexture2D* Texture=UTexture2D::CreateTransient(${graph.width},${graph.height},PF_A32B32G32R32F,NAME_None,Bytes);
      if(!Texture) return false; Texture->SRGB=false; Texture->UpdateResource(); InitialTextures.Add(Texture); }`);
    let hlsl=r.hlsl;
    const fields=[];
    hlsl=hlsl.replace(/cbuffer\s+\w+\s*:\s*register\([^)]*\)\s*\{([\s\S]*?)\};/g,(_,body)=>{
      return body.replace(/(\w+)\s+(\w+)\s*:\s*packoffset\([^)]*\);/g,(_,type,field)=>{
        if ((r.hlsl.match(new RegExp(`\\b${field}\\b`,'g'))??[]).length===1) return '';
        const key=field.replace(/^_\d+_/,''), u=v.uniforms?.[key];
        if(!u || !/^float[234]?$/.test(type)) throw new Error(`Native graph requires explicit float/vector uniform: ${v.name}.${key}`);
        const index=uniformKeys.length; uniformKeys.push(`${v.name}.${key}`);
        const values=Array.isArray(u.value)?u.value:[u.value]; defaults.push(`FVector4f(${[...values,...Array(4-values.length).fill(0)].map(value=>`${Math.fround(value)}f`.replace(/^(\-?\d+)f$/,'$1.0f')).join(',')})`);
        fields.push({type,field,index,binding:u.binding,nativeName:`EfxUniform_${key}`}); return `${type} ${field};`;
      });
    }).replace(/ : register\([^)]*\)/g,'');
    const resources=r.reflection.textures??[];
    // UE's parameter parser requires identifiers to begin with a letter.
    // SPIRV-Cross's autogenerated _NN_uniform/_texture_sampler names do not.
    const renames={efx_Output:'EfxOutput'};
    for(const f of fields) renames[f.field]=f.nativeName;
    for(const t of resources){renames[t.name]=`EfxTexture_${t.name}`;renames[`_${t.name}_sampler`]=`EfxSampler_${t.name}`;}
    hlsl=rewriteIdentifiers(hlsl,renames);
    add(`Shaders/Pass${i}.usf`,'#include "/Engine/Public/Platform.ush"\n'+hlsl);
    const cppType={float:'float',float2:'FVector2f',float3:'FVector3f',float4:'FVector4f'};
    const declarations=[...fields.map(f=>`SHADER_PARAMETER(${cppType[f.type]}, ${f.nativeName})`),...resources.flatMap(t=>[`SHADER_PARAMETER_RDG_TEXTURE(Texture2D, EfxTexture_${t.name})`,`SHADER_PARAMETER_SAMPLER(SamplerState, EfxSampler_${t.name})`]),'SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, EfxOutput)'];
    const shader=`F${module}Pass${i}`;
    passClasses.push(`class ${shader}: public FGlobalShader {
      DECLARE_GLOBAL_SHADER(${shader}); SHADER_USE_PARAMETER_STRUCT(${shader},FGlobalShader);
      BEGIN_SHADER_PARAMETER_STRUCT(FParameters,)\n${declarations.join('\n')}\nEND_SHADER_PARAMETER_STRUCT()
      static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters){ return IsFeatureLevelSupported(Parameters.Platform,ERHIFeatureLevel::SM5); }
    }; IMPLEMENT_GLOBAL_SHADER(${shader},"/Plugin/${module}/Pass${i}.usf","main",SF_Compute);`);
    const assignments=fields.map(f=>{
      let value;
      if(f.binding==='time') value='Time'; else if(f.binding==='delta') value='Delta'; else if(f.binding==='frame') value='float(Frame)';
      else { const vec=`Values[${f.index}]`; value=f.type==='float'?`${vec}.X`:f.type==='float2'?`FVector2f(${vec}.X,${vec}.Y)`:f.type==='float3'?`FVector3f(${vec}.X,${vec}.Y,${vec}.Z)`:vec; }
      return `Params->${f.nativeName}=${value};`;
    });
    for(const t of resources) {
      const index=graph.variables.findIndex(dep=>dep.name===t.name), dep=graph.variables[index];
      const addr={clamp:'AM_Clamp',repeat:'AM_Wrap',mirror:'AM_Mirror'};
      assignments.push(`Params->EfxTexture_${t.name}=Current[${index}]; Params->EfxSampler_${t.name}=TStaticSamplerState<${dep.filter==='linear'?'SF_Bilinear':'SF_Point'},${addr[dep.wrapS]},${addr[dep.wrapT]},AM_Clamp>::GetRHI();`);
    }
    dispatch.push(`{ auto* Params=Builder.AllocParameters<${shader}::FParameters>();
      ${assignments.join('\n')} Params->EfxOutput=Builder.CreateUAV(Next[${i}]);
      TShaderMapRef<${shader}> Shader(GetGlobalShaderMap(GMaxRHIFeatureLevel));
      ClearUnusedGraphResources(Shader,Params);
      FComputeShaderUtils::AddPass(Builder,RDG_EVENT_NAME("${v.name}"),Shader,Params,FIntVector(${Math.ceil(graph.width/8)},${Math.ceil(graph.height/8)},1)); }`);
    add(`Compiler/Pass${i}.glsl`,r.glsl); files.set(`Compiler/Pass${i}.spv`,r.spirv);
    add(`Compiler/Pass${i}.reflection.json`,JSON.stringify(r.reflection,null,2));
  }
  add(`${module}.uplugin`,JSON.stringify({FileVersion:3,Version:1,VersionName:'1.0',FriendlyName:`Elfentier GPU ${graph.name}`,CanContainContent:false,Modules:[{Name:module,Type:'Runtime',LoadingPhase:'PostConfigInit'}]},null,2));
  add(`Source/${module}/${module}.Build.cs`,`using UnrealBuildTool;
public class ${module}:ModuleRules { public ${module}(ReadOnlyTargetRules Target):base(Target) {
PCHUsage=PCHUsageMode.NoPCHs;
PublicDependencyModuleNames.AddRange(new[]{"Core","CoreUObject","Engine","RenderCore"});
PrivateDependencyModuleNames.AddRange(new[]{"RHI","Projects"});
RuntimeDependencies.Add("$(PluginDir)/Resources/*.bin",StagedFileType.NonUFS);
} }`);
  add(`Source/${module}/Public/${base}.h`,`#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "RenderCommandFence.h"
#include "${base}.generated.h"
class UTexture2D; class UTextureRenderTarget2D; class UMaterialInterface; class UWorld; struct F${module}State;
UCLASS(ClassGroup=(Rendering),meta=(BlueprintSpawnableComponent))
class ${module.toUpperCase()}_API ${cls}:public UActorComponent { GENERATED_BODY()
public:
  UFUNCTION(BlueprintCallable,Category="Elfentier") bool Reset();
  UFUNCTION(BlueprintCallable,Category="Elfentier") bool Step(float DeltaSeconds,int32 Iterations=1);
  UFUNCTION(BlueprintCallable,Category="Elfentier") bool SetUniform(FName Name,FVector4 Value);
  UFUNCTION(BlueprintPure,Category="Elfentier") UTextureRenderTarget2D* GetOutput(FName Variable) const;
  UFUNCTION(BlueprintCallable,Category="Elfentier") static TArray<FString> ValidateMaterial(UMaterialInterface* Material);
  UFUNCTION(BlueprintCallable,Category="Elfentier") static bool PrepareWorldForCapture(UWorld* World);
  UFUNCTION(BlueprintCallable,Category="Elfentier") static FString GetMaterialSource(UMaterialInterface* Material);
  virtual void BeginDestroy() override; virtual bool IsReadyForFinishDestroy() override;
private:
  UPROPERTY(Transient) TArray<TObjectPtr<UTexture2D>> InitialTextures;
  UPROPERTY(Transient) TArray<TObjectPtr<UTextureRenderTarget2D>> Outputs;
  TSharedPtr<F${module}State,ESPMode::ThreadSafe> State;
  TArray<FVector4f> Uniforms; float Time=0; uint32 Frame=0; FRenderCommandFence Fence;
};`);
  const names=graph.variables.map(v=>`FName(TEXT("${v.name}"))`).join(',');
  const uniforms=uniformKeys.map(key=>`FName(TEXT("${key}"))`).join(',');
  add(`Source/${module}/Private/${module}.cpp`,`#include "${base}.h"
#include "Modules/ModuleManager.h"
#include "Interfaces/IPluginManager.h"
#include "ShaderCore.h"
#include "GlobalShader.h"
#include "ShaderParameterStruct.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "RHIStaticStates.h"
#include "Engine/Texture2D.h"
#include "Engine/TextureRenderTarget2D.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "TextureResource.h"
#include "Materials/Material.h"
#include "MaterialShared.h"
#include "Engine/World.h"
#if WITH_EDITOR
#include "AssetCompilingManager.h"
#endif
class F${module}Module:public IModuleInterface { void StartupModule() override {
  const auto Plugin=IPluginManager::Get().FindPlugin(TEXT("${module}"));
  check(Plugin); AddShaderSourceDirectoryMapping(TEXT("/Plugin/${module}"),FPaths::Combine(Plugin->GetBaseDir(),TEXT("Shaders")));
} }; IMPLEMENT_MODULE(F${module}Module,${module})
${passClasses.join('\n')}
struct F${module}State { TArray<TRefCountPtr<IPooledRenderTarget>> Textures; };
static const TArray<FName> VariableNames={${names}};
static const TArray<FName> UniformNames={${uniforms}};
bool ${cls}::Reset(){
  check(IsInGameThread()); InitialTextures.Empty(); Outputs.Empty(); Uniforms={${defaults.join(',')}};
  const FString BaseDir=IPluginManager::Get().FindPlugin(TEXT("${module}"))->GetBaseDir();
  ${init.join('\n')}
  for(int32 Index=0;Index<${graph.variables.length};++Index){
    auto* Target=NewObject<UTextureRenderTarget2D>(this); Target->RenderTargetFormat=RTF_RGBA32f; Target->bCanCreateUAV=true;
    Target->InitAutoFormat(${graph.width},${graph.height}); Target->UpdateResourceImmediate(true); Outputs.Add(Target);
  }
  State=MakeShared<F${module}State,ESPMode::ThreadSafe>(); State->Textures.SetNum(${graph.variables.length}); Time=0;Frame=0; return true;
}
bool ${cls}::SetUniform(FName Name,FVector4 Value){
  check(IsInGameThread()); const int32 Index=UniformNames.IndexOfByKey(Name);
  if(!State||Index==INDEX_NONE||!FMath::IsFinite(Value.X)||!FMath::IsFinite(Value.Y)||!FMath::IsFinite(Value.Z)||!FMath::IsFinite(Value.W)) return false;
  Uniforms[Index]=FVector4f(Value);return true;
}
UTextureRenderTarget2D* ${cls}::GetOutput(FName Name) const {const int32 Index=VariableNames.IndexOfByKey(Name);return Outputs.IsValidIndex(Index)?Outputs[Index].Get():nullptr;}
bool ${cls}::Step(float DeltaSeconds,int32 Iterations){
  check(IsInGameThread()); if(!State||!FMath::IsFinite(DeltaSeconds)||DeltaSeconds<0||Iterations<1||Iterations>64)return false;
  TArray<FTextureResource*> Initial; TArray<FTextureRenderTargetResource*> Targets;
  for(const auto& Texture:InitialTextures)Initial.Add(Texture->GetResource());
  for(const auto& Target:Outputs)Targets.Add(Target->GameThread_GetRenderTargetResource());
  const auto RenderState=State; const auto Values=Uniforms; const float StartTime=Time; const uint32 StartFrame=Frame;
  ENQUEUE_RENDER_COMMAND(ElfentierGraphStep)([RenderState,Initial,Targets,Values,StartTime,StartFrame,DeltaSeconds,Iterations](FRHICommandListImmediate& RHICmdList){
    FRDGBuilder Builder(RHICmdList); TArray<FRDGTextureRef> Current;
    for(int32 Index=0;Index<${graph.variables.length};++Index){
      if(RenderState->Textures[Index])Current.Add(Builder.RegisterExternalTexture(RenderState->Textures[Index]));
      else Current.Add(RegisterExternalTexture(Builder,Initial[Index]->TextureRHI,TEXT("InitialState")));
    }
    for(int32 Iteration=0;Iteration<Iterations;++Iteration){
      const float Delta=DeltaSeconds; const float Time=StartTime+Iteration*Delta;const uint32 Frame=StartFrame+Iteration;
      TArray<FRDGTextureRef> Next; for(int32 Index=0;Index<${graph.variables.length};++Index)
        Next.Add(Builder.CreateTexture(FRDGTextureDesc::Create2D(FIntPoint(${graph.width},${graph.height}),PF_A32B32G32R32F,FClearValueBinding::None,TexCreate_ShaderResource|TexCreate_UAV),TEXT("NextState")));
      // Every pass samples Current. Swap only after the complete epoch.
      ${dispatch.join('\n')}
      Current=MoveTemp(Next);
    }
    for(int32 Index=0;Index<${graph.variables.length};++Index){
      auto* Target=RegisterExternalTexture(Builder,Targets[Index]->GetRenderTargetTexture(),TEXT("Output"));
      AddCopyTexturePass(Builder,Current[Index],Target);Builder.QueueTextureExtraction(Current[Index],&RenderState->Textures[Index]);
    }
    Builder.Execute();
  });
  Time+=DeltaSeconds*Iterations; Frame+=Iterations; return true;
}
void ${cls}::BeginDestroy(){Super::BeginDestroy();Fence.BeginFence();}
bool ${cls}::IsReadyForFinishDestroy(){return Fence.IsFenceComplete()&&Super::IsReadyForFinishDestroy();}
TArray<FString> ${cls}::ValidateMaterial(UMaterialInterface* Material){
  if(!Material) return {TEXT("Null material")};
  auto* Resource=Material->GetMaterialResource(GMaxRHIShaderPlatform);
  if(!Resource) return {TEXT("Material resource unavailable")};
  Resource->FinishCompilation();
  if(!Resource->GetGameThreadShaderMap()) return Resource->GetCompileErrors().IsEmpty()?TArray<FString>{TEXT("Material has no compiled shader map")}:Resource->GetCompileErrors();
  return Resource->GetCompileErrors();
}
bool ${cls}::PrepareWorldForCapture(UWorld* World){
  if(!World) return false;
#if WITH_EDITOR
  FAssetCompilingManager::Get().FinishAllCompilation();
#endif
  World->SendAllEndOfFrameUpdates();FlushRenderingCommands();return true;
}
FString ${cls}::GetMaterialSource(UMaterialInterface* Material){
  FString Source;
#if WITH_EDITOR
  if(Material){auto* Resource=Material->GetMaterialResource(GMaxRHIShaderPlatform);if(Resource)Resource->GetMaterialExpressionSource(Source);}
#endif
  return Source;
}
`);
  add('graph.json',JSON.stringify(graph,null,2)+'\n');
  add('native-port-report.json',JSON.stringify({format:'elfentier_native_gpu_port_v1',graph:graph.name,pass_count:compiled.passes.length,
    languageCompiled:true,nativeBuildVerified:false,gpuExecutionVerified:false,semantics:graph.semantics,
    component:cls.slice(1),uniforms:uniformKeys,variables:graph.variables.map(v=>v.name)},null,2)+'\n');
  add('README.md',`# ${module}\n\nCopy this directory to your UE project's Plugins/${module}, then build the Editor target.\nRuntime component: ${cls.slice(1)}. Call Reset(), Step(delta, iterations), GetOutput(variable).\nSetUniform("variable.uniform", Vector4) changes constant bindings. Time/delta/frame bindings are automatic.\nEach iteration is one GPUComputationRenderer.compute() epoch; all passes read the previous epoch.\nInitial values are staged as NonUFS files. Results are RGBA32f native render targets.\nNo browser, GLSL compiler or SPIRV-Cross is required at runtime.\nCheck native-port-report.json: generated source requires a UE build and GPU validation.\n`);
  const root=await writeBundle({files},out); return {root,module,component:cls.slice(1),compiled};
}
